name: Sync Branch

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: Crimzega/SulvicFunkin
          token: ${{ secrets.PAT }}
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Sync branch
        run: |
          git remote add upstream https://github.com/FunkinCrew/Funkin.git
          git fetch upstream
          git checkout forked
          git merge upstream/main --allow-unrelated-histories
          git push origin forked
